languageCode = 'en-us'
baseURL = 'https://sebkrantz.github.io/blog'
publishDir = "docs"

title = 'Blog of Sebastian Krantz'
theme = 'hugo-blog-awesome'

disqusShortname = "blog-of-sebastian-krantz" # <-- must match your Disqus site shortname
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "^README", "\\.R$", "\\.Rproj$", ".git"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Navigation menu
[menu]
[[menu.main]]
  pageRef = "/"
  url = '/'
  weight = 10
[[menu.main]]
  pageRef = "about"
  name = 'About'
  url = '/about/'
  weight = 20

[params]
  # Theme configuration
  description = "A personal blog built with Hugo and the Blog Awesome theme"
  keywords = ["blog", "hugo", "awesome"]
  
  # Author configuration
  [params.author]
    name = "Sebastian Krantz"
    avatar = "images/profile.png"
    bio = "A passionate developer and writer"
    location = "Earth"
    
  # Social links
  [params.social]
    github = "https://github.com/SebKrantz"
    bluesky = "https://bsky.app/profile/sebkrantz.bsky.social"
    mastodon = "https://fosstodon.org/@sebkrantz"
    linkedin = "https://www.linkedin.com/in/sebastian-krantz-phd-91a08aa9/"
  
  # Theme features
  enableSearch = true
  enableCodeCopy = true
  enableMath = true
  enableMermaid = true
  
  # Appearance
  colorScheme = "auto"  # auto, light, dark
  fontSize = "medium"   # small, medium, large
  
  # Home page
  homePage = "/"    # posts, about, contact
  
  # Navigation
  showReadingTime = true
  showWordCount = true
  showPostNav = true
  showBreadCrumbs = true
  showCodeCopy = true
  showShareButtons = true
  showRelatedPosts = true
  showTableOfContents = true

buildFuture = true
